version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.6.10-management
    ports:
      - "4369:4369"
      - "25672:25672"
      - "5671-5672:5671-5672"
      - "15671-15672:15671-15672"
    networks:
      - internal
  redis:
    container_name: redis
    image: redis:4.0
    ports:
      - "6379:6379"
    networks:
      - internal
  job:
    container_name: job
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmtjobsvc:release
    ports:
      - "${JOB_PORT}:8020"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - TOTALMOBILE_BASEURL=http://mock:8000/
      - REDIS_HOST=redis
    depends_on:
      - rabbit
  jobv4:
    container_name: jobv4
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmtjobsvcv4:4-release
    ports:
      - "${JOBV4_PORT}:8025"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - TOTALMOBILE_BASEURL=http://mock:8000/
      - REDIS_HOST=redis
    depends_on:
      - rabbit
      - postgres
  adapter:
    container_name: adapter
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmtrmadapter:release
    ports:
      - "${ADAPTER_PORT}:8010"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
  mock:
    container_name: mock
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmttmmock:snapshot
    ports:
      - "${MOCK_PORT}:8000"
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
  outcome:
    container_name: outcome
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmtoutcomesvc:2-release
    ports:
      - "${OUTCOME_PORT}:8030"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
      - postgres
  csvserv:
    container_name: csvserv
    image: eu.gcr.io/census-gcr-fwmt-gateway/census-rm-fwmtcsvservice:release
    ports:
      - "${CSVSERV_PORT}:8060"
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbit
      - REDIS_HOST=redis
    depends_on:
      - rabbit
networks:
  internal:
    driver: bridge
