version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.6.10-management
    ports:
      - "4369:4369"
      - "25672:25672"
      - "5671-5672:5671-5672"
      - "15671-15672:15671-15672"
    networks:
      - internal
  job:
    container_name: job
    image: eu.gcr.io/census-fwmt-ci-233109/census-rm-fwmtjobsvc:snapshot
    ports:
      - "${JOB_PORT}:8020"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - TOTALMOBILE_BASEURL=http://mock:8000/
    depends_on:
      - rabbit
  adapter:
    container_name: adapter
    image: eu.gcr.io/census-fwmt-ci-233109/census-rm-fwmtrmadapter:snapshot
    ports:
      - "${ADAPTER_PORT}:8010"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - rabbit
  mock:
    container_name: mock
    image: eu.gcr.io/census-fwmt-ci-233109/census-rm-fwmttmmock:snapshot
    ports:
      - "${MOCK_PORT}:8000"
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbit
    depends_on:
      - rabbit
  outcome:
    container_name: outcome
    image: eu.gcr.io/census-fwmt-ci-233109/census-rm-fwmtoutcomesvc:snapshot
    ports:
      - "${OUTCOME_PORT}:8030"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - rabbit
  csvserv:
    container_name: csvserv
    image: eu.gcr.io/census-fwmt-ci-233109/census-rm-fwmtcsvservice:snapshot
    ports:
      - "${CSVSERV_PORT}:8060"
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbit
    depends_on:
      - rabbit
networks:
  internal:
    driver: bridge
