version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:3.6.10-management
    ports:
      - "4369:4369"
      - "25672:25672"
      - "5671-5672:5671-5672"
      - "15671-15672:15671-15672"
    networks:
      - internal
  job:
    container_name: job
    image: eu.gcr.io/census-ci/census-rm-fwmtjobsvc
    ports:
      - "${JOB_PORT}:9999"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
      - TOTALMOBILE_BASEURL=http://mock:9099/
    depends_on:
      - rabbit
  adapter:
    container_name: adapter
    image: eu.gcr.io/census-ci/census-rm-fwmtrmadapter
    ports:
      - "${ADAPTER_PORT}:9094"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - rabbit
  mock:
    container_name: mock
    image: eu.gcr.io/census-ci/census-rm-fwmttmmock
    ports:
      - "${MOCK_PORT}:9099"
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbit
    depends_on:
      - rabbit
  feedback:
    container_name: feedback
    image: eu.gcr.io/census-ci/census-rm-fwmtfeedbacksvc
    ports:
      - "${FEEDBACK_PORT}:9990"
    networks:
      - internal
    environment:
      - RABBITMQ_HOSTNAME=rabbit
    depends_on:
      - rabbit
networks:
  internal:
    driver: bridge
